### ISSUE TITLE
Не работает чат, в чем может быть проблема?

### ISSUE THREAD

**Issue by dixakman** [shevernitskiy/wasdtv#1]
Добрый день!
Не работает чат, в чем может быть проблема?

Дебажил библиотеку, в итоге вечно ловлю ошибку:

Connecting...
connect_error: Error: websocket error
attempt: 1

и так постоянно

Есть мысли?

**Comment by shevernitskiy** [comment]
Проблема давно наблюдается? У меня сейчас даже в вебе сокет не конектит.

**Comment by dixakman** [comment]
> Проблема давно наблюдается? У меня сейчас даже в вебе сокет не конектит.

Я думаю дня 3-4 где-то

Смотрите прикол

1. Если запускаем чатбота, подождем до ошибки
2. Зайдем на васду, чат не подключится, васда как будто бы блочит на N минут
3. Чтобы снова заработало, меняем IP адрес
4. Зайдем на васду, и проверим чат, он будет работать
5. Но если снова запустим чатбот, подождем ошибку, то он снова "заблочит" ип адрес

**Comment by dixakman** [comment]
Самое смешное, что если просто на js + html сделать, то все будет работать
Я предполагаю что есть проблема с совместимостью... но очень много разных версия socket.io-client перепробовал, ни одна не сработала

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>

    <script>
        const socket = io('https://chat.wasd.tv', {
            autoConnect: !1,
            path: "/socket.io/",
            timeout: 2e4,
            reconnecting: !0,
            reconnectionDelayMax: 2e3,
            transports: ["websocket"]
        });

        console.log('Connecting...');

        socket.connect();

        socket.on('connect', () => {
            console.log("WebSocket connect")
        });

        socket.on('reconnect', () => {
            console.log(`reconnect`);
        });

        socket.on('disconnect', () => {
            console.log(`disconnect`);
        });

        socket.on('connect_error', (err) => {
            console.log(`connect_error: ${err}`);
        });

        socket.on('error', (err) => {
            console.log(`error: ${JSON.stringify(err)}`);
        });

        socket.on('reconnect_attempt', (attempt) => {
            console.log(`attempt: ${attempt}`);
        });

        socket.on('reconnect_error', (error) => {
            console.log(`reconnect_error: ${error}`);
        });

        socket.on("reconnect_failed", () => {
            console.log(`reconnect_failed`);
        });

    </script>
    <title>Title</title>
</head>
<body>

</body>
</html>

**Comment by shevernitskiy** [comment]
Пишите в дев суппорт васда. Скорее всего васд опять вертит настройки защиты. Меня уже один раз при написании либы блочило, проблемы были аналогичные. Через веб заходило, через либу нет. Думаю в вебе есть какие-то куки или токены защиты (поэтому там работает). Блочило так же по IP.
Васд там сам пока не знает, какие правила защиты будут. На мою просьбу их как-то формализовать и озвучить они ответили отказом. Не вижу сейчас, чтобы что-то в апи поменялось, может так оно и есть.

**Comment by dixakman** [comment]
> Пишите в дев суппорт васда. Скорее всего васд опять вертит настройки защиты. Меня уже один раз при написании либы блочило, проблемы были аналогичные. Через веб заходило, через либу нет. Думаю в вебе есть какие-то куки или токены защиты (поэтому там работает). Блочило так же по IP. Васд там сам пока не знает, какие правила защиты будут. На мою просьбу их как-то формализовать и озвучить они ответили отказом. Не вижу сейчас, чтобы что-то в апи поменялось, может так оно и есть.

В принципе ожидаемый ответ от васды)))
отписался в саппорт, может и ответят

**Comment by shevernitskiy** [comment]
Написал неделю назад в поддержку васда, ответа нет до сих пор. В дискорде сообщили, что сейчас много дел и ответить мне не могут.
При коннекте через голый веб сокет получаем `ECONNRESET` на стадии `TLS handshake`. Это говорит о том, то вероятность причины с новыми настройками доступа со стороны васда 99%.

**Comment by dixakman** [comment]
> Написал неделю назад в поддержку васда, ответа нет до сих пор. В дискорде сообщили, что сейчас много дел и ответить мне не могут. При коннекте через голый веб сокет получаем `ECONNRESET` на стадии `TLS handshake`. Это говорит о том, то вероятность причины с новыми настройками доступа со стороны васда 99%.

Мне так и не ответила))) У вас прям какой-то приоритетный "доступ" к их поддержке)

**Comment by shevernitskiy** [comment]
Сегодняшняя проверка показала, что чат работает. Вероятно васд что-то открутил обратно, потому как я никаких изменений не вносил.
